<?php

declare(strict_types=1);

use Practice\Comments\Block\CommentTemplate;

/** @var CommentTemplate $block */
$dateFormat = 'Y D, d M Y H:i:s';
$comments = $block->getComments();
$isCommentsEmpty = empty($comments);
$commentUpdateUrl = $block->getUrl('comments/index/edit');
$commentDeleteUrl = $block->getUrl('comments/index/delete');
$commentCreateUrl = $block->getUrl('comments/index/create');
?>

<a href="<?= $commentCreateUrl ?>">Add comment</a>
<?php if ($isCommentsEmpty) : ?>
    <p>No comments found!</p>
<?php else: ?>
    <table>
        <tr>
            <td>Name</td>
            <td>Email</td>
            <td>Title</td>
            <td>Comment</td>
            <td>Created at</td>
            <td>Last Revision</td>
            <td>Actions</td>
        </tr>
        <?php foreach ($comments as $comment) : ?>
            <tr>
                <td><?= $comment->getAuthorName() ?></td>
                <td><?= $comment->getAuthorEmail() ?></td>
                <td><?= $comment->getCommentTitle() ?></td>
                <td><?= $comment->getComment() ?></td>
                <td><?= $comment->getCreatedAt()->format($dateFormat) ?></td>
                <td><?= $comment->getUpdatedAt()->format($dateFormat) ?></td>
                <td>
                    <form action="<?= $commentUpdateUrl ?>" method="post">
                        <label>
                            <input type="text" name="id" hidden value="<?= $comment->getCommentId() ?>"/>
                        </label>
                        <button class="action-transparent" type="submit">Edit</button>
                    </form>
                    <form action="<?= $commentDeleteUrl ?>" method="post">
                        <label>
                            <input type="text" name="id" hidden value="<?= $comment->getCommentId() ?>"/>
                        </label>
                        <button class="action-transparent" type="submit">Delete</button>
                    </form>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
